When invoking commands under a debugger, exceptions are no longer trapped.
